package org;

/**
 * This class was automatically generated by the data modeler tool.
 */
@org.kie.workbench.common.services.datamodeller.annotations.Label(value = "mdo_02")
public class mdo_02  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    @org.kie.workbench.common.services.datamodeller.annotations.Label(value = "text 02")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String text_02;
    
    @org.kie.workbench.common.services.datamodeller.annotations.Label(value = "text 01")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String text_01;

    public mdo_02() {
    }

    public mdo_02(java.lang.String text_01, java.lang.String text_02) {
        this.text_01 = text_01;
        this.text_02 = text_02;
    }


    
    public java.lang.String getText_02() {
        return this.text_02;
    }

    public void setText_02(  java.lang.String text_02 ) {
        this.text_02 = text_02;
    }
    
    public java.lang.String getText_01() {
        return this.text_01;
    }

    public void setText_01(  java.lang.String text_01 ) {
        this.text_01 = text_01;
    }




}