package org;

/**
 * This class was automatically generated by the data modeler tool.
 */
@org.kie.workbench.common.services.datamodeller.annotations.Label(value = "mdo_01")
public class mdo_01  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    @org.kie.workbench.common.services.datamodeller.annotations.Label(value = "value 02")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String value_02;
    
    @org.kie.workbench.common.services.datamodeller.annotations.Label(value = "value 03")
    @org.kie.api.definition.type.Position(value = 2)
    private org.mdo_02 value_03;
    
    @org.kie.workbench.common.services.datamodeller.annotations.Label(value = "value 01")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String value_01;

    public mdo_01() {
    }

    public mdo_01(java.lang.String value_01, java.lang.String value_02, org.mdo_02 value_03) {
        this.value_01 = value_01;
        this.value_02 = value_02;
        this.value_03 = value_03;
    }


    
    public java.lang.String getValue_02() {
        return this.value_02;
    }

    public void setValue_02(  java.lang.String value_02 ) {
        this.value_02 = value_02;
    }
    
    public org.mdo_02 getValue_03() {
        return this.value_03;
    }

    public void setValue_03(  org.mdo_02 value_03 ) {
        this.value_03 = value_03;
    }
    
    public java.lang.String getValue_01() {
        return this.value_01;
    }

    public void setValue_01(  java.lang.String value_01 ) {
        this.value_01 = value_01;
    }




}