package org.jbpm.michaelsproject;

/**
 * This class was automatically generated by the data modeler tool.
 */
@org.kie.workbench.common.services.datamodeller.annotations.Label(value = "subdmod")
public class subDMOD  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    @org.kie.workbench.common.services.datamodeller.annotations.Label(value = "wert 01")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String w_01;
    
    @org.kie.workbench.common.services.datamodeller.annotations.Label(value = "wert 02")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String w_02;

    public subDMOD() {
    }

    public subDMOD(java.lang.String w_01, java.lang.String w_02) {
        this.w_01 = w_01;
        this.w_02 = w_02;
    }


    
    public java.lang.String getW_01() {
        return this.w_01;
    }

    public void setW_01(  java.lang.String w_01 ) {
        this.w_01 = w_01;
    }
    
    public java.lang.String getW_02() {
        return this.w_02;
    }

    public void setW_02(  java.lang.String w_02 ) {
        this.w_02 = w_02;
    }
}